name: TntTag
version: '1.0'
main: net.fliuxx.tntTag.TntTag
api-version: '1.21'
authors: [ Fl1uxxNoob ]
description: TntTag plugin
commands:
  tnttag:
    description: Comandi per gestire TNTTag
    usage: /tnttag <start|stop|reload|gui>
